portworx/px-fuse

dev.c
fuse_i.h
pxd.c
pxd.h

Support device queues if a queue depth is passed in. If the queue depth passed in 0, then it reverts to the old mode.

Support device queues

---

pxd.c

- Limit the number of devices attached

- Fix device enumerate

---

pxd.c
pxd.h

- Version upgrade

---

dev.c
fuse_i.h

remove unused code

---

dev.c
fuse_i.h
pxd.c

reduce number of memory allocations

allocate fuse req in mq request

---

dev.c
fuse_i.h
pxd.c

check request type once instead of check type, set field, check field

---

dev.c
fuse_i.h
pxd.c
pxd.h

keep backward compatible opcode for device attach

---

Makefile.in
dev.c
fuse_i.h
pxd.c
pxd.h
pxd_compat.h
pxd_core.h
pxd_fastpath.c
pxd_fastpath.h
pxd_fastpath_stub.c

This PR provides extensions for configuration from user space.

fastpath kernel driver changes (3/8)

---

Makefile.in
dev.c
fuse_i.h
pxd.c
pxd.h
pxd_compat.h
pxd_core.h
pxd_fastpath.c
pxd_fastpath.h
pxd_fastpath_stub.c

fastpath kernel driver changes (2/8)

---

pxd_fastpath.c

fix compile

---

pxd.c
pxd_core.h

simplify abort fix; use delayed_work instead of

---

pxd.c

fix compilation on 5.1+ kernels

---

Makefile.in
pxd_fastpath.c

1/ replace warning to info message in makefile.
2/ fix compilation in later kernels
3/ fix minor accounting bug.

fix minor compilation and incorrect accounting

---

pxd_fastpath.c

compilation fix for 4.9 kernel (#88)

---

pxd.c
pxd_fastpath.c
pxd_fastpath.h
pxd_fastpath_stub.c

* compilation failure in centos 7.6 3.10.0-957.el7.x86_64 kernel - fixed
* IO assert - fixed
* export io distribution across thread context.
* general code cleanup.

fix compile, assert and code cleanup

---

io.c
io.h

re-initialize volatile part of context on open

fix duplicate open check, return ebusy on dup open

---

pxd_fastpath.c

keep reference to the file during IO

---

pxd.c
pxd_compat.h

Fix conflict...
PWX-14825: Merge in change from master c8709d0 PR #137 to fix 5.7.0 compilation issue.

Compilation changes for kernel 5.7 (#137)

---

pxd.c
pxd_compat.h
pxd_fastpath.c

Compile fixes for SLES/OpenSuse 4.12.x kernels.

Suse compile fixes

---

Makefile.in
pxd.c
pxd_compat.h
pxd_fastpath.c

Compile fixes for 5.8.x, 4.12.x & 4.13.x EL7 kernels && Merge in master 'Suse compile fixes PR #147 (bc03ffa)'

Compile fixes 4x 5x kernels

---

Makefile.in
README.md
test/pxd_test.cc

UTs for attach/detach, read/write operations.

Add pxd tests

---

pxd_compat.h
pxd_fastpath.c

https://portworx.atlassian.net/browse/PWX-16799
Validate current pxvolume state before proceeding with volume cleanup and restart IOs.

harden vol cleanup interface

---

pxd.c

cherry-pick 108f0df2d0a7e795771d204cff4b2db1cdcc51cf from 2.6

Compilation issues with 5.9.8-flatcar. (#168)

---

pxd.c
pxd_fastpath.c

Compilation fixes for changes 5.9.x kernel changes.

PWX-16992: Fix compile issues for 5.9.6-1.el7.elrepo.x86_64 kernel.

---

pxd.c
pxd_fastpath.c

Change version check to Fix undefined declarations for 5.8 kernels. Fix iot not declared error.

5.8.x fixes master

---

pxd_compat.h
pxd_fastpath.c

fix compilation break for bio_op() in 4.4 kernel.

compile fix for bio_op

---

io.c
pxd.c
pxd_compat.h
pxd_fastpath.c

* compilation fixes in 5.9/5.10 kernel
cherry picked changes from master for compilation fixes.

PWX-18535: compilation fixes upto 5.10 kernel (#189)

---

dev.c
fuse_i.h
io.c
io.h
pxd.h
pxd_compat.h
pxd_io_uring.h

Fix master px-fuse submodule for compilation.
Compile tested master. 
jenkins run failed for some other issue.
https://jenkins.portworx.dev/job/DEV/job/Porx-02/642/console
Brings in the following changes from private branch to master:
```
commit 47961a204d6ae1847bb5490467e4d06154071731 (HEAD -> origin/iorthread1, origin/iorthread1)
Author: Maxim Kozlovsky <mkozlovsky@purestorage.com>
Date:   Tue Jan 5 09:23:41 2021 -0800
ioring offload thread support
commit c6ee65f50dd0458514571fc65637abe68c61dbd1
Author: Maxim Kozlovsky <mkozlovsky@purestorage.com>
Date:   Fri Dec 4 11:48:17 2020 -0800
support for passing parameters to initialize ioring context
```

fix master px-fuse broken build

---

pxd.h

PWX-19152: update pxd version to 12, version 11 has mmap req queue disabled

---

pxd.c

handle forced detach. 
previous vfs_stat() calls are not consistent in their results.
Revised to use lookup_bdev.
Closes # https://portworx.atlassian.net/browse/PWX-20602
Porx PR: https://github.com/portworx/porx/pull/7843
root@bionic:/home/lns/srcs/src/github.com/portworx/porx/src/gdfs# ./t --gtest_filter=KernelQueueTest.forced_detach
Note: Google Test filter = KernelQueueTest.forced_detach
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from KernelQueueTest
[ RUN      ] KernelQueueTest.forced_detach
[       OK ] …

PWX-20602: handle forced detach

---

pxd.c
pxd.h

code optimization, remove need for a separate call to understand fastpath status.
Closes #

piggy back fastpath status during device attach.

---

io.c

Discard on dmthin with iouring never worked. file->f_inode is not valid for for raw block devices.
Closes # PWX-20795
```
root@prabir-VirtualBox:~/git/go/src/github.com/portworx/porx# cat /etc/pwx/config.json | grep iouring
"iouring": 1,
root@prabir-VirtualBox:~/git/go/src/github.com/portworx/porx#
root@prabir-VirtualBox:~/git/go/src/github.com/portworx/porx# ./bin/pxctl v c v1
Volume successfully created: 130639449186015851
root@prabir-VirtualBox:~/git/go/src/github.com/portworx/porx# 
root@prabir-VirtualBox:~/git/go/src/github.com/portworx/porx# lsblk | grep 130639449186015851
│   ├─pwx0-130639449186015851             253:5    0     1G  0 lvm   
│ …
```

PWX-20795: Fix iouring block device discard

---

fuse_i.h
pxd.c
pxd_bio.h
pxd_bio_blkmq.c
pxd_bio_makereq.c
pxd_fastpath.c
pxd_fastpath.h
pxd_fastpath_stub.h

Closes # https://portworx.atlassian.net/browse/PWX-21201 - fix compilation issue

PWX-21201 - compile fix/disable fastpath code during compile time

---

fuse_i.h
pxd.c
pxd_bio.h
pxd_bio_blkmq.c
pxd_bio_makereq.c
pxd_core.h
pxd_fastpath.c
pxd_fastpath.h
pxd_fastpath_stub.h

cherry-picked changes from master.
Closes #
PWX-21175

PWX-21175: handle kernel crash in fastpath + compilation fix (#227)

---

pxd.c

v2.7 & v2.8 do fuse does not compile under the 5.11 kernel.   We need this to support fc33 latest kernel releases on OKD for PX 2.9.x.
PWX-20576
This is pulled from @sulakshm change: https://github.com/portworx/px-fuse/commit/c220a5a8faa192f5b9cf581911870ac55e7efe87.  There was another change associated with 5.11 in that PR which was made in file io.c but file does not exist in this branch so I left it out.

PWX-20267: fix compilation from master c220a5a8 for 5.11.x kernels

---

io.c
io.h
pxd.h

add support for providing partial region and extending the mapping
later while reusing the same fixed region.
Closes #

add ioctl for registering fixed buffers with iouring

---

dev.c
fuse_i.h
pxd.c

Disable response queue it will be implemented differently by responding
directly after completing i/o without going through the user space.
Closes #

PWX-21888 disable response queue

---

pxd.c
pxd.h

Set discard granularity to 64k (needed for thin vol)

---

pxd.c

cherry picked changes from master to 2.10 branch
Closes #

discard settings for dmthin

---

pxd.c
pxd.h

Map REQ_PREFLUSH to PXD_FLAGS_PREFLUSH and REQ_FUA to PXD_FLAGS_FLUSH

PWX-22291 Update handling of write request with REQ_PREFLUSH and REQ_FUA flags

---

pxd.h

This reverts commit 3cdf004cf2cb1a87e098ff3f9a2ef6eb88c488f5.

Revert "PWX-22291 Map PXD_FLAGS_SYNC to PXD_FLAGS_FUA"

---

io.c

Handles unaligned discards directly in the uring kernel driver part.
This does not affect btrfs path since it is file based.
Since only dmthin is block based, patching here address both handling unaligned discards and process it asynchronously as well.
Changes to px-storage through https://github.com/portworx/porx/pull/8690 may not be needed at all.
Closes # https://portworx.atlassian.net/browse/PWX-22764
https://jenkins.portworx.dev/job/DEV/job/Porx-01/1059/

PWX-22764: handle unaligned discards

---

Makefile.in
dev.c
pxd.c

- El9 support 
Closes #
PWX-22489 

PWX-21857 - El9 compilation fixes

---

pxd.c
pxd.h

Allow UTs to send requests to the control device

---

pxd.c

Px-fuse changes for building and running on kernel >= 5.15 
Closes #
PWX-21857

Incorporate kernel 5.15 api changes

---

Makefile.in
pxd.c

Compilation fixes for RHEL kernels 5.(16/17).x  EL8 and EL9
Closes #

RHEL compilation fixes.

---

pxd.c

Add 5.13 and 5.14 support
Closes #

5.13 contains fsync

---

Makefile.in

add logic to trim remotes/origin from branch name if it exists
Closes #PWX-28534, #PTX-14654

add logic to trim remotes/origin from branch name if it exists

---

pxd.c

device detach deadlock detected.
```
[root@ip-10-13-107-180 ~]# ps aux | grep ' D'
root      4760  0.0  9.1 2293496 746128 ?      DLl  Mar31   0:34 /usr/local/bin/px-storage
root      5145  0.0  0.0  10116  3380 ?        D    Mar31   0:00 blkid
root     14485  0.0  0.0 112832  2268 pts/0    S+   01:39   0:00 grep --color=auto  D
root     25989  0.0  0.0  10116  3328 ?        D    Mar31   0:00 blkid
```
```
Mar 31 16:54:57 ip-10-13-107-180 kernel: task:blkid           state:D stack:    0 pid:25989 ppid:     1 flags:0x00000004
Mar 31 16:54:57 ip-10-13-107-180 kernel: Call Trace:
Mar 31 16:54:57 ip-10-13-107-180 kernel: <TASK>
Mar 31 16:54:57 ip-10-13-107-180 kernel: __schedule+0x29e/0x7e0
Mar 31 16:54:57 ip-10-13-107-180 kernel: schedule+0x4e/0xb0
Mar …
```

PWX-30236: kill pxd_ctl_mutex usage

---

pxd.c

see notes from https://github.com/portworx/px-fuse/pull/273
Closes #
https://portworx.atlassian.net/browse/PWX-30236
https://jenkins.pwx.dev.purestorage.com/job/DMTHIN/view/LimitandScale/job/TestLimitAndScaleVolOps-DMTHIN-RELEASE/19/

PWX-30236: kill usage of pxd_ctl_mutex

---

io.c
io.h
pxd_io_uring.h

PWX-30241 poll support

---

kiolib.c
pxd.c
pxd_bio_blkmq.c
pxd_compat.h

Px-fuse changes for Rocky and Rhel 5.14.0-{70,162,284}.xxx
Closes #
PWX-33144

PWX-33144: 5.14.0-{70,162,284}.xxx px-fuse compilation fixes.

---

pxd.c

* PWX-35570: fix compilation
PWX-35570: cherry-pick #300
Closes # PWX-35570

PWX-35570: cherry-pick #300

---

pxd.c
pxd_trace.h

**What this PR does / why we need it**
Support for 6.5 kernels. 
Closes #
PWX-35356

PWX-35356: Fix compilation issues for 6.5.12-100.fc37.x86_64

---

pxd.c

cherry picked changes from 3.1.0 to master.
Closes #
PWX-35639: handle stuck device removal

PWX-35639: handle stuck device removal

---

Makefile.in
pxd.c
pxd_bio_blkmq.c
pxd_fastpath.c

Changes to build SLES15 Sp5 pkgs would not build for SLES15 Sp4 pkgs.   Add define to check for Sp5.
Closes #
PWX-35683

PWX-35683: Compile fixes for SLES15 sp4 & sp5 and azure

---

pxd.c
pxd_bio.h
pxd_bio_blkmq.c
pxd_fastpath.c
pxd_fastpath.h

same work for fastpath perf opt, moved to master.
Closes #

fastpath perf optimize

---

pxd.c
pxd_trace.h

cherry pick https://github.com/portworx/px-fuse/pull/316 to ~~3.1.2~~ branch
reopened and rebased to right branch v3.2.0
cherry picked changes to release branch.
Closes #PWX-37281

PWX-37281: fix tracebacks in kernels during dev add and removals

---

dev.c
kiolib.c
pxd.c

Fix compilation issues  for 6.8 and 6.9 kernels.   
Closes #

PWX-36736: kernel v6.8/9 support

---

pxd.c
pxd.h

Closes #PWX-37390: px-storev2 discard for large thin pool chunks

PWX-37390: px-storev2 discard for large thin pool chunks

---

dev.c

more details : https://github.com/portworx/px-fuse/issues/332
Closes #

PWX-42778: fix for incorrect len in __fuse_notify_read_data

---

dev.c
pxd.c
pxd_core.h

dup of the PR against main
Closes #

PWX-43068_v3.2.3

---

pxd_bio_blkmq.c

Associate the clone bio with a block group
Closes # PWX-42957

PWX-42957: Associate the clone bio with a block group

---

pxd.c

allow disabling discards on pxd device.
Linked porx PR: https://github.com/pure-px/porx/pull/14751
Closes # PWX-43085

PWX-43085: allow disabling discards

---

pxd.c
pxd.h

allow disabling discards, cherry pick from main.
https://github.com/portworx/px-fuse/pull/349
https://github.com/portworx/px-fuse/pull/340
Closes # PWX-43085

PWX-43085: allow disabling discards (#349)

---

pxd_bio_blkmq.c

compilation fail
Closes # PWX 42957

PWX 42957 - cherry pick to v3.3.0 branch

---

pxd_bio_blkmq.c
pxd_compat.h

cherry pick https://github.com/portworx/px-fuse/pull/358
Closes # PWX-43573

PWX-43573: fastpath flush io fixup

---

pxd.c
pxd_compat.h
pxd_fastpath.c

(cherry picked from commit 5fbcff34228c9c8ebf41c2af2de60e66bda55547)
Closes # PWX-44121

PWX-44121: Fix fuse build for RHEL 9.6 + 5.14.0-570.17.1.el9_6 (#362)

---

pxd.h

Update fuse to allow 1024 attachments
Closes #PWX-43864

Update fuse to allow 1024 attachments

---

pxd.h

Update fuse to allow 1024 attachments (#365)

---

pxd.h

This reverts commit a71bd87fef71062dccb4a31cbcecf37d49eb4ab8.
Closes #

Revert "Update fuse to allow 1024 attachments (#365) (#369)"
