portworx/px-fuse

- iov_iter.h
- pxd_compat.h
This branch contains two fixes:
- Fix a kernel version number comparison in pxd_compat.h to define HAVE_BVEC_ITER for Linux kernels 3.14.x and later instead of just 3.16.x and later.  This fixed compilation for all kernel headers from kernel.ubuntu.com for Linux 3.14.x and 3.15.x.
- Fix some redeclaration clashes that occur in iov_iter.h when compiling Linux kernels 3.16.x and Linux 3.17.x kernels from kernel.ubuntu.com and also the 3.16 kernel used in Debian 8.6 Jessie.
> Compilation fixes for Linux 3.14 - Linux 3.18

- dev.c
This reverts commit 2b7dad519668f9b7f7b877fcd60a32f7b8ab92d1.
> Revert "use non blocking allocations for fuse requests - GFP_ATOMIC"

- dev.c
- pxd.c
The request structure is already zeroed after allocating, so need to zero some of the fields of the structure again.  Also some duplicate code in some functions are moved to a common function.  Also removing some unnecessary code.
> Pxd minor cleanup

- dev.c
Try to pick as many requests each time requests are copied from kernel to user space.  This seems to improve our throughput.
> Try to pick up as many requests in every iteration

- dev.c
- fuse_i.h
- pxd.c
isreply field set as 1 always, so that could be removed along with associated code processing it.
move some code which does not need lock protection, out of the lock.
and some misc cleanup.
> Remove unused isreply field from requests and associated processing.

- dev.c
- fuse_i.h
- pxd.c
refcount on the init request is decremented twice, which could cause memory corruption.  Fix that by not freeing the request more than once.
Also the refcount on the requests is unnecessary which could be removed along with code processing that.
> Fix a kernel memory corruption and remove unnecessary refcount for requests

- dev.c
- fuse_i.h
- pxd.c
PXD driver can convert writes of zero blocks as discard requests and avoid unnecessary transfer of zeroes from kernel to user space.
> Convert writes of zeros to discard request

- dev.c
Version isn't completely reliable either but that's the best we can do for now.
> CONFIG_HARDENED_USERCOPY isn't reliable, use kernel version instead for whitelist annotations

- pxd.c
pxd_update_stats uses, 'part_stat_inc' & 'part_stat_add'.  Those functions changes in EL8.    Need to use this define to get around them for now.
> PWX-8766: Use __PX_BLKMQ__ define in pxd_update_stats.

- pxd.c
- pxd_fastpath.c
- pxd_fastpath.h
IBM mq fio profile (iodepth=1), with fdatasync=1 has very poor performance even with fastpath enabled. The reason is mainly attributed to scheduling delay because further work is scheduled on the same cpu to keep cache active. But the performance hit of moving within the same numa node is minimal, and also, if the current cpu is active, other cpu in the same numa node can schedule further processing of IO and complete it fast. This change improves the performance to expected levels.
iops kernel IO:
4k      8k     64k
ext4 on device: 42012   36426   14395
px with ext4:    5082    4375    1912
px faspath ext4: 30.8k|25.7k|10.3k
> merge ibm perf patch changes back into review code.

- Makefile.in
This is needed because we build according to the version specified by the KERNELPATH env var rather than the actual kernel that is running $(uname -r).  So we should use the kernel path version if it exists to determine defines used to build.  If it does not exist or cannot be found then use $(uname -r).
Also enable BLKMQ changes for 5.x kernel builds.
> Use kernel path version for determining defines.

- dev.c
- fuse_i.h
- pxd.c
remove page descriptor handling from requests
pxd init was the only request type that was using the fields
> special case pxd init handling

- dev.c
- fuse_i.h
- pxd.c
- pxd.h
remove init handling from data path
bump module version 
https://github.com/portworx/porx/pull/4856 for corresponding user space changes
> use ioctl instead of request for init call

- dev.c
- fuse_i.h
- pxd.c
this does not require locks while hash does
per cpu id allocators
> use array to lookup request by id

- dev.c
- fuse_i.h
- pxd.c
don't need union anymore since init is handled by ioctl
> remove unused fields

- Makefile.in
- dev.c
- fuse_i.h
- pxd.c
- pxd.h
- pxd_compat.h
- pxd_core.h
- pxd_fastpath.c
- pxd_fastpath.h
- pxd_fastpath_stub.c
when px comes along and opens the px control file, an implicit fuse init message is pushed to the userspace. This has no associated bio and parsing some debug states failed with null pointer exception.
> fuse init call has no bio, handle exception (5/8)

- Makefile.in
- dev.c
- fuse_i.h
- pxd.c
- pxd.h
- pxd_compat.h
- pxd_core.h
- pxd_fastpath.c
- pxd_fastpath.h
- pxd_fastpath_stub.c
export collected kernel io statistics through the sys attributes file path.
```
ubuntu@pdc1-intel4:/opt/pwx$ cat /sys/devices/pxd/1/active
nactive: 0/11601190, [write: 11601150, flush: 11601150(nop: 0), fua: 3867051, discard: 0, preflush: 7734099], switched: 0, slowpath: 0
ubuntu@pdc1-intel4:/opt/pwx$ cat /sys/devices/pxd/1/congested
congested: 0/0
ubuntu@pdc1-intel4:/opt/pwx$ cat /sys/devices/pxd/1/sync
sync: 0/0 (enabled)
ubuntu@pdc1-intel4:/opt/pwx$ cat /sys/devices/pxd/1/writesegment
write segment size(bytes): 4194304
ubuntu@pdc1-intel4:/opt/pwx$
```
> export stats through sys attrs (4/8)

- pxd.c
are not interrupt safe
schedule abort as a work_struct
> can't call fuse_conn_abort() from timer since connection locks

- Makefile.in
- dev.c
- fuse_i.h
- pxd.c
- pxd.h
- pxd_compat.h
- pxd_core.h
- pxd_fastpath.c
- pxd_fastpath.h
- pxd_fastpath_stub.c
This is a series of PRs to get fast path driver changes into mainline, revised to latest master again.
This series addresses:
1/ kernel version checks - enable fastpath only if kernel > 4.0
2/ extend to support backing file open mode (direct or buffered etc)
3/ some additional statistics.
This initial PR prepares the fuse driver for fast path integration
> fastpath kernel driver changes (1/8)

- pxd.c
- pxd_fastpath.c
Backward compat issues fix.
1) using newer px/px-storage with older px-fuse results in device attach call fails.
This is because new px-storage uses PXD_ADD_EXT opcode which is unknown with older px-fuse driver.
Reverted attach to only use PXD_ADD for now.
This is part of porx PR: https://github.com/portworx/porx/pull/4987
2) during device removal, there is a kernel dump sometimes as below.
This is because fastpath contexts are not initialized during device add, but are cleaned up during device remove. Made context initialization mandatory, and operations to check and act only if enabled on fastpath.
BVT Pass: https://jenkins.portworx.co/job/DEV/job/Porx-08/66
Crash traceback
```
[Thu Dec 19 18:15:03 2019] For pxd device …
```
> fix fastpath context uninitialized for nativepath crash

- dev.c
- fuse_i.h
- pxd.c
allows user to submit new requests after abort and deadlock.
use syncrhonize_rcu() to make sure changes are seen by all threads
don't need to lock around checking connected status anymore
> fix the race where we would reset fc->connected in abort which 

- dev.c
- fuse_i.h
- pxd.c
does not require spin locks for user space accesses
does not require intra node pointers which will allow the queue
to be accessed directly from user space eventually
> use lock free queue for pending requests instead of linked list 

- dev.c
- fuse_i.h
- pxd.c
can't update from request_pending() since this is called
concurrently from poll()
cleanup barrier calls
> update reader write pointer from receive function

- pxd.c
Fuse request allocation may fail, prevent null ptr access.
> Set fastpath for valid fuse requests only

- dev.c
- fuse.h
- fuse_i.h
- pxd.c
- pxd.h
create v1 structures with previous version definitions
> remove unnecessary fields from fuse_in_header and pxd_rdwr_in

- dev.c
- pxd.c
remove unnecessary locks in waits
remove unnecessary checks for connected in read and poll,
since connected set on open, !connected is impossible
> remove duplicate checks for connected, check once in send_nowait()

- dev.c
- fuse_i.h
- pxd.c
in preparation to map the queue into user space
> store request directly in the queue instead of pointer

- Makefile.in
- dev.c
- pxd.c
- pxd.h
- pxd_core.h
- pxd_fastpath.c
Commit: https://github.com/torvalds/linux/commit/736706bee3298208343a76096370e4f6a5c55915
removed reference to get_ds(), hardcoded value to KERNEL_DS.
Without this change, px-fuse failing compilation in 5.1+ Linux kernels.
1/ fix log strings for capitalization
2/ fix fastpath counters
3/ fix fastpath init for extended device add with paths.
4/ bump version as pxd interface structs changed.
> minor changes to px-fuse based on testing fastpath

- pxd_fastpath.c
> compilation fix for 4.9 kernel

- pxd_core.h
- pxd_fastpath.c
The changes handle read only targets more gracefully very early at the request submission time with the px device. This also avoids btrfs kernel tracebacks for requests submitted to it, while read only.
**Test Logs**
```
root@ip-172-31-61-165:/home/ubuntu/srcs/src/github.com/portworx# pxctl v l
ID                      NAME            SIZE    HA      SHARED  ENCRYPTED       IO_PRIORITY     STATUS                          SNAP-ENABLED    PUBLIC
1013358237278815083     fpclone1        1 GiB   1       no      no              HIGH            up - detached                   no              true
751443242257173254      fpsnap1         1 GiB   1       no      no              HIGH            up - detached                   no …
```
> handle read only targets correctly

- pxd_fastpath.c
modify device suspend to not wait forever, change to retry/warn and continue.
> stop waiting forever during suspend

- pxd.c
- pxd_fastpath.c
- pxd_fastpath.h
- pxd_fastpath_stub.c
If the queue limits are not properly set, then it may be possible to submit an incompatible block IO directly with the backing devices.
This shall results in bio too large error messages.
```
[root@PDC1-SM1 px-fuse]# cat /sys/block/pxd\!pxd831186063849924602/queue/max_sectors_kb
128
[root@PDC1-SM1 px-fuse]# cat /sys/block/pxd\!pxd831186063849924602/queue/max_segments
33
[root@PDC1-SM1 px-fuse]# cat /sys/block/pxd\!pxd831186063849924602/queue/logical_block_size
4096
[root@PDC1-SM1 px-fuse]# cat /sys/block/pxd\!pxd831186063849924602/queue/max_segment_size
65536
[root@PDC1-SM1 px-fuse]# cat /sys/block/pxd\!pxd831186063849924602/queue/max_discard_segments
1
[root@PDC1-SM1 px-fuse]# cat …
```
> adjust pxd device queue limits wrt backing device

- io.c
- io.h
- pxd.c
- pxd_core.h
it is enough to create just one device
> since io context is allocated dynamically

- pxd_compat.h
- pxd_fastpath.c
A compile time hack to find the proper signature for lookup_bdev.
Failed compilation in ubuntu 18 distro as below. 
There doesn't exist any single compile time macro to check and decide on this.
```
/home/max/workspace/src/github.com/portworx/porx/src/gdfs/px_fuse/Makefile:97: kernel fast path enabled, current kernel version 4.15.0-96-generic need minimum 4.0
/home/max/workspace/src/github.com/portworx/porx/src/gdfs/px_fuse/pxd_fastpath.c: In function ‘pxd_fastpath_adjust_limits’:
/home/max/workspace/src/github.com/portworx/porx/src/gdfs/px_fuse/pxd_fastpath.c:1557:11: error: too few arguments to function ‘lookup_bdev’
bdev = lookup_bdev(pxd_dev->fp.device_path[i]);
^~~~~~~~~~~
In file included from …
```
> handle different api signature for lookup_bdev

- dev.c
- fuse_i.h
- pxd.c
- pxd_core.h
- pxd_fastpath.c
- pxd_fastpath.h
Minor code cleanup and reorg as below.
1) for a device attached, fastpath state could switch to native path dynamically, hence this flag cannot be treated as  state as to how the block device is registered. Separated this condition to be part of fastpath context.
2) the io completion path only relies on whether request queue is used or not, it is better a state within fuse request and further simplifies code. Introduced  a new flag that is part of fuse request, using_blkque that is always persistent and can decide code flow to complete block requests.
3) fixed compilation issues while enabling debug prints.
4) adjust queue limits is only needed if the backing device is a block device, if its a file, it can be left as is.
5) pxd_init_fastpath_target() revised to disable/enable fastpath …
> fastpath driver cleanup

- pxd_compat.h
- pxd_fastpath.c
1/ fix for blk_endio() signature change for 4.3+ kernel.
2/ fix for adjust queue depth which calls lookup_dev whose signature change across distribution by avoiding it.
**TestLogs**
a) compiles on 4.20
```
[lns@PDC1-SM1 px-fuse]$ uname -r
4.20.13-1.el7.elrepo.x86_64
[lns@PDC1-SM1 px-fuse]$ make
Kernel version 4.20 supports blkmq driver model.
Kernel fast path enabled, current kernel version 4.20.13-1.el7.elrepo.x86_64 need minimum 3.10
make -C /usr/src/kernels/4.20.13-1.el7.elrepo.x86_64  M=/home/lns/srcs/src/github.com/portworx/px-fuse modules
make[1]: Entering directory `/usr/src/kernels/4.20.13-1.el7.elrepo.x86_64'
Kernel version 4.20 supports blkmq driver model.
Kernel fast path enabled, current kernel version …
```
> fix compile issue

- pxd.c
- pxd_compat.h
- pxd_fastpath.c
- pxd_fastpath.h
- pxd_fastpath_stub.c
With the below changes addressed the high latency while in fastpath.
Results are tabulated here under optimized heading:
https://portworx.atlassian.net/wiki/spaces/PC/pages/899121235/Performance+study+on+fastpath+volumes
a) removed the queueing logic and if request if for block device requests can go through direct without any queueing.
b) for file based backing device, needs to be queued to avoid deadlocks.
c) optimize and remove all locks in the regular IO path.
d) use work queue instead for IO queueing and processing file IO.
> optimize IO scheduling path 

- dev.c
- pxd.c
Running good so far:
https://jenkins.portworx.co/job/DEV/job/Porx-05/213
The crash only applies if the block device is registered as a blkmq device.
> address use after free (fuse_req)

- dev.c
- fuse_i.h
- pxd.c
- pxd.h
Cherry-pick from master.
px-fuse master has too many other changes, hence branching it for v2.6.
> Resize ioctl (#126)

- dev.c
- fuse_i.h
- io.c
- pxd.c
- pxd_core.h
- pxd_io_uring.h
goes with porx change:
https://github.com/portworx/porx/pull/6098
**test logs**
kernel: 
```
lns@xenial:~/srcs/src/github.com/portworx/porx/src/gdfs$ uname -r
4.20.17-042017-generic
lns@xenial:~/srcs/src/github.com/portworx/porx/src/gdfs$
```
***ut logs***
```
root@xenial:/home/lns/srcs/src/github.com/portworx/porx/src/gdfs# ./t --gtest_filter=KernelQueueTest.switch_io*
Note: Google Test filter = KernelQueueTest.switch_io*
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from KernelQueueTest
[ RUN      ] KernelQueueTest.switch_io
[       OK ] KernelQueueTest.switch_io (12121 ms)
[ RUN      ] KernelQueueTest.switch_io2
[       OK ] KernelQueueTest.switch_io2 (12135 ms)
[----------] 2 tests from KernelQueueTest (24256 ms total) …
```
> iouring provide a in kernel io switch path based on ctx, unique id

- pxd.c
- pxd_fastpath_stub.c
We need to be able to set the timeout to a higher value. This is required when a maintenance operation is undergoing on node which would keep it down for more than 10 minutes.
> Allow greater than 300sec timeout values

- pxd.c
- pxd.h
- pxd_fastpath.c
- pxd_fastpath.h
- pxd_fastpath_stub.c
As replica paths are attached during kernel device add, also specify if the replica is local.
If the device attached is local and is a single replica, then do not failover during IO errors.
With fastpath disabled:
https://jenkins.portworx.co/job/DEV/job/Porx-05/247
With fastpath enabled:
https://jenkins.portworx.co/job/DEV/job/Porx-03/286
> Ensure no failover if IO to local replica

- pxd.c
During UT runs some of the tests fail with a race condition between restarting requests during new connection and previous abort running in parallel.
Below is the kernel crash traceback.
```
[Fri Jul 24 10:27:26 2020] pxd_control_open: pxd-control-0(1) open OK
[Fri Jul 24 10:27:26 2020] Device 1 added ffff8e74ccf60000 with mode 0x2 fastpath 1 npath 0
[Fri Jul 24 10:27:26 2020] device 1 setting up fastpath target with mode 0x48002(LARW), paths 0
[Fri Jul 24 10:27:26 2020] For pxd device 1 IO suspended
[Fri Jul 24 10:27:26 2020] For pxd device 1 IO resumed
[Fri Jul 24 10:27:26 2020] device 1 setup through nativepath (0)
[Fri Jul 24 10:27:26 2020] pxd device 1: adjusting queue limits nfd 0
[Fri Jul 24 10:27:27 2020] …
```
> fix race during restart with previous abort

- dev.c
- pxd.c
- pxd.h
- pxd_fastpath.c
- pxd_fastpath.h
- pxd_fastpath_stub.c
Add new interface to allow suspend/resume IO of fastpath device from userspace.
porx userspace should release on restart if device found in suspend state and restart any state machine that require device to be IO suspended in fast path.
This goes with https://github.com/portworx/porx/pull/6306
> fastpath suspend/resume from userspace

- pxd.c
fix the path with kernel version checks.
> bio_split signature mismatch on 3.10 kernels

- dev.c
- pxd.c
- pxd.h
- pxd_fastpath.c
- pxd_fastpath.h
- pxd_fastpath_stub.c
When devices are suspended, replica paths are synced inline. 
This PR takes the sync to a background thread run from a work queue.
There is an associated timeout, (1min) currently, after which sync and suspend operation is aborted.
> run flush in background with a timeout

- Makefile.in
- pxd_compat.h
Travis builds uses the 4.15.0-1077-gcp kernel and we failed to build on that one.  Issue was also seen on autopilot automation run using 4.15.0-1092-azure.
> Fix compilation failure on 4.15.0-1077-gcp & 4.15.0-1092-azure.

- pxd.c
- pxd_core.h
- pxd_fastpath.c
- pxd_fastpath.h
Remove support for background sync. This code path is not needed anymore, has been disabled since long time.
The rootcause is block device registered for fastpath does not honour queue depth and gets enqueued very large IO, which keeps syncing in the background forever even after the original app is done. This has been handled now through suspending IO to device if pending IO is over a congestion threshold.
> remove support for bg sync

- io.c
- pxd.c
Distro testing failed to find/build KO for 4.18.0-193.el8.x86_64.   Add define check for EL8 for  backport to 4.10.0-xxx
> El8 compilation fixed for 4.18.0-193.el8.x86_64 kernels.

- pxd.h
The below struct change though allows proper alignment results in breaking backward compatibility.
The below change puts the definition to earlier, more details on failing upgrade test and analysis in jira.
https://portworx.atlassian.net/browse/PWX-16058
> align struct to old release

- pxd.c
Exporting in progress IO on a device for userspace px-storage to identify whether there are still any active IO on the device.
This is important while switching iopath between userspace and kernel on fastpath capable device.
> export inprogress IO on a device

- pxd.c
- pxd_core.h
- pxd_fastpath.c
- pxd_fastpath.h
- pxd_fastpath_stub.c
The final set of changes to get fastpath failover stable. dmthin BVT has been running longer than before.
https://jenkins.portworx.dev/job/DEV/job/Porx-04/313/console
porx side changes will be separate on 
https://github.com/portworx/porx/pull/6505
once more tests pass.
> fastpath failover 

- pxd.c
- pxd.h
- pxd_compat.h
- pxd_fastpath.c
- pxd_fastpath.h
- pxd_fastpath_stub.c
Fastpath volume operations failure cleanups.
If in the final stage of attaching a fastpath volume fails, then it cannot be immediately allowed to service IO in the native path, because SAN setup has put targets in fastpath mode, wherien the file handles are closed.
So they will remain in suspended state until a final cleanup request is issued.
Also do not ever update fastpath state without informed userspace.
This has been tested with userspace https://github.com/portworx/porx/pull/6505
> fastpath fail scenario cleanup

- pxd_fastpath.c
sector_t changed from unsigned long to u64 in 5.2+ kernel.
fix compilation error while printing sector info on error.
On 4.20 
```
lns@bionic:~/srcs/src/github.com/portworx/px-fuse$ make
Kernel version 4.20 supports blkmq driver model.
Kernel fast path enabled, current kernel version 4.20.17-042017-generic need minimum 3.10
make -C /usr/src/linux-headers-4.20.17-042017-generic  M=/home/lns/srcs/src/github.com/portworx/px-fuse modules
make[1]: Entering directory '/usr/src/linux-headers-4.20.17-042017-generic'
Kernel version 4.20 supports blkmq driver model.
Kernel fast path enabled, current kernel version 4.20.17-042017-generic need minimum 3.10
CC [M]  /home/lns/srcs/src/github.com/portworx/px-fuse/pxd.o
CC [M] …
```
> fix compilation at 5.x kernel

- pxd.c
Fix compilation issue 'REQ_OP_READ' undeclared  & REQ_OP_WRITE' undeclared 
/
> PWX-16752: Add kernel version check to use the right request op enums

- pxd_fastpath.c
reads were reported always zero. Fixed the param for stats.
Goes with px stats change.
> fix stats param

- pxd.c
- pxd.h
https://portworx.atlassian.net/browse/PWX-17109
This change adds a new IOCTL to help tag a process as a IO_FLUSHER. When tagged as IO_FLUSHER, the kernel memory allocation does not try to wait on dirty pages to flushed. This helps to get away with buffers that were dirty as a result of mkfs on newly created pxd device. The wait on flush of these dirty buffers would lead to a cyclic dependency and thereby cause a deadlock
> pwx-17109 : support for making a process into a IO flusher

- pxd.c
PWX-17271:  Compilation fixes for flatcar with kernel 5.9.8-flatcar.
Note needed to disable below for kernel 5.9.0 and above: 
// add hooks to control congestion only while using fastpath
q->backing_dev_info->congested_fn = pxd_device_congested;
q->backing_dev_info->congested_data = pxd_dev;
> PWX-17271: Compilation issues with 5.9.8-flatcar.

- pxd.c
- pxd_fastpath.c
While using non blk mq device registration, block device limits may not be honoured always.
It was partially handled for few versions with bio_split.
Extending the bits to honour all versions with this changeset.
**Test Logs**
```
[root@ip-70-0-83-247 px-fuse]# pxctl v c -s 10 -r 3 vol2r3
Volume successfully created: 686228160905618492
[root@ip-70-0-83-247 px-fuse]# pxctl v i -e vol2r3
Volume                   :  686228160905618492
Name                     :  vol2r3
Size                     :  10 GiB
Format                   :  ext4
HA                       :  3
IO Priority              :  HIGH
Creation time            :  Dec 8 13:58:45 UTC 2020
Shared                   :  no
Status                   :  up
State …
```
> honour block device limits for all cases

- pxd.c
- pxd_fastpath.c
- pxd_fastpath.h
Compilation fix for 5.9 kernel is incomplete with no method registered to handle IO for the virtual px block device.
This PR introduces the submit_io method to complete it.
> PWX-17949: fix bdev entry func for 5.9 kernel

- pxd.c
Active IO to px device, px goes down and stays down, abort handler gets run.
In which case, it is possible for a recursive fc->lock to be taken.
pxd_abort_context(fc->lock)->fuse_end_queued_requests->request_end->fuse_put_unique(fc->lock)
fc->lock need not be taken while running pxd_abort_context, micro operations that work on 'fc' takes the lock appropriately.
if px were to come back again, there is a cancel_delayed_work_sync first up that ensures abort handler is not running.
And new requests that are received while px is disconnected are like wise handled with fc->lock taken for each micro ops.
No need to take this lock globally while running abort handler.
PWX BUG: https://portworx.atlassian.net/browse/PWX-18262
```
Jan …
```
> address recursive fc->lock path

- dev.c
- fuse_i.h
- pxd.c
when fastpath devices are switched iopath, the fuse context that gets used for communication between porx and px-fuse does not get freed resulting in following exception during rmmod eventually.
```
[Thu Jan  7 16:34:30 2021] BUG pxd_fuse_request (Tainted: G           OE    ): Objects remaining in pxd_fuse_request on __kmem_cache_shutdown()
```
> PWX-18027: fix fuse 'req' leak

- pxd_fastpath.c
- pxd_fastpath.h
fastpath specific.
imported remote replicas may not support discards.
For example, iscsi imported disks support only writesame/writezero but do not support discard.
Currently px-fuse driver shall report EOPNOTSUPP to the caller.
Instead handle this more gracefully by converting request to supported operation for each backing device.
```
root@bionic:/home/lns# pxctl host attach v1
Volume successfully attached at: /dev/pxd/pxd855549171283095927
root@bionic:/home/lns# pxctl v i -e v1
Volume                   :  855549171283095927
Name                     :  v1
Size                     :  1.0 GiB
Format                   :  none
HA                       :  1
IO Priority              :  HIGH
Creation time            :  Jan 7 …
```
> PWX-18057: px-fastpath support better discard handling

- io.c
- pxd.c
- pxd_compat.h
- pxd_fastpath.c
https://portworx.atlassian.net/browse/PWX-18535
In the common IO path, few compilation fixes for 5.9/5.10 kernel. 
compilation passed in the following kernels. logs below.
```
[root@ip-70-0-39-218 ~]# ls !$
ls /usr/src/kernels/
4.14.186-146.268.amzn2.x86_64  4.18.0-193.23.1.el8_2.x86_64      4.18.0-80.1.2.el8_0.x86_64   5.7.0-1.el7.elrepo.x86_64  5.9.0-1.el7.elrepo.x86_64
4.18.0-147.20.1.el8_1.x86_64   4.18.0-193.24.1.el8_2.dt1.x86_64  5.10.0-1.el7.elrepo.x86_64   5.7.0-1.el8.elrepo.x86_64  5.9.0-1.el8.elrepo.x86_64
4.18.0-147.el8.x86_64          4.18.0-193.el8.x86_64             5.10.0-1.el8.elrepo.x86_64   5.8.0-1.el7.elrepo.x86_64
4.18.0-193.14.2.el8_2.x86_64   4.18.0-80.11.1.el8_0.x86_64 …
```
> compilation fixes upto 5.10 kernel

- dev.c
- fuse_i.h
- pxd.c
Issue:
Stuck requests from block layer but fuse has none.
Assertion with invalid uid seen.
JIRA:
https://portworx.atlassian.net/browse/PWX-18756
Root cause:
1/ rcu usage incorrect, code accessing protected variables naked causing stale values to be read.
fc->connected and fc->allow_disconnected though protected with rcu read and sync calls (not all places),
were never protected against compiler optimization by accessing them WRITE_ONCE(), READ_ONCE() macros.
There are many places where updates to these happen, hence removed them altogether and switched to use memory barriers instead.
2/ when new requests get submitted in disconnected state, uids are still allocated, request initialized and freed again.
This can all be avoided by early return.
NOTES:
```
[root@ip-70-0-69-50 px-fuse]# pxctl …
```
> PWX-18756 fix race in restart and new req processing

- dev.c
- fuse_i.h
- pxd.c
* address race between restart and new req processing
cherry picked changes from 2.7.0 to master
https://github.com/portworx/px-fuse/pull/190
> PWX-18756 fix race in restart and new req processing (#190)

- pxd.c
noticed spin lock already locked in abort context and never freed, thereby stalling a px restart.
https://jenkins.portworx.dev/job/PX2-RELEASE/view/PX2-RELEASE-Cloudsnap/job/FVT-MN-ObjectStore-NEXT-PX2-RELEASE/
referenced to the original fuse 2.7.0 that regressed:
https://github.com/portworx/px-fuse/pull/199/files#r594439302
```
Mar 15 11:58:53 ip-70-0-41-103 portworx: 2021-03-15 11:58:53,540 INFO success: pxdaemon entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
Mar 15 11:59:09 ip-70-0-41-103 kernel: NMI watchdog: BUG: soft lockup - CPU#3 stuck for 24s! [systemd-udevd:2759]
Mar 15 11:59:09 ip-70-0-41-103 kernel: Modules linked in: intel_rapl(-) floppy(-) rpcsec_gss_krb5 nfsv4 dns_resolver nfs fscache af_packet_diag netlink_diag vsock_diag tcp_diag udp_diag …
```
> pxd abort handler leaves fc->lock in locked state.

- dev.c
- fuse_i.h
- pxd.c
- pxd.h
- pxd_fastpath.c
px-fastpath specific cleanups:
1/ during failover from fastpath, open file handles are not closed (relies on disableFastPath() to perform the needed)
2/ io callbacks get scheduled from interrupt context during completion, need intr protection for handling failover.
3/ cleans up unused code.
https://portworx.atlassian.net/browse/PWX-18937
PASSED:
https://jenkins.portworx.dev/job/DEV/job/Porx-01-caching/435/ - btrfs smoke 3.10 kernel
https://jenkins.portworx.dev/job/DEV/job/Porx-01-caching/436 - dmthin smoke 4.18 kernel
https://jenkins.portworx.dev/job/DEV/job/Porx-01-caching/437 - dmthin smoke 5.7 kernel
> PWX-18937: px-fastpath driver cleanups

- pxd_compat.h
Fix compilation issue with 4.15.0-141-generic kernel.
PWX-19639
This should not be merged in yet... Need to check this change against Suse 4.12.x kernel builds.
> Compilation fix for 4.15.0-141-generic.

- Makefile.in
- io.c
- pxd.c
Fix compilation issue.
a) revalidate_disk_size failure (not needed from 5.11)
b) stats interface changes -- this path is now no longer supported in master (having switched to blkmq fastpath)
c) blk_freeze_queue_start -- only available from 4.12 (used in fastpath) unless distros backported changes.
```
[lns@clone8 px-fuse]$ git checkout -b master origin/master
Branch 'master' set up to track remote branch 'master' from 'origin'.
Switched to a new branch 'master'
[lns@clone8 px-fuse]$ make
Kernel version 5.11 supports blkmq driver model.
make  -C /usr/src/kernels/5.11.3-1.el8.elrepo.x86_64  M=/home/lns/srcs/src/github.com/portworx/px-fuse modules
make[1]: Entering directory …
```
> fix compilation

- pxd.c
Adds stale device checks before adding new device to kernel.
checks for both actual block device and its sysfs device existence.
if they are present, during a device attach, then device attach will crash in add disk path inside the kernel.
This window may open up if forced detach gets used.
Closes #
part of https://portworx.atlassian.net/browse/PWX-20602
> PWX-20602: pre-check stale devices before add

- io.c
https://portworx.atlassian.net/browse/PWX-20756
hit register file exception as below
```
#0  0x00007f387a1a418b in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f387a183859 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f387a183729 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007f387a194f36 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x000056005d0a63ee in px::ioring::Context::register_file (
this=<optimized out>, fd=<optimized out>) at gdsd/pxd_io.cc:144
#5  0x000056005d0e2c79 in px::target::FileHandle::FileHandle (
```
The number of replica targets is 521 on that node.
Px in master, opens each file in two modes this doubles the count. …
> PWX20756: iouring increase file limit

- pxd.c
compilation fix for lookup_bdev.
In ubuntu alone this function has been extended with one additional arg to check for permission.
To address this, px-fuse module will always push with 2 args while calling lookup_bdev, while the actual kernel function can decide whether to use one or both args. This though is a hackish way, is clean and should work always.
Introduced part of https://github.com/portworx/px-fuse/pull/218
Ubuntu kernel commit for reference:
```
commit 6bdf7d686366556020b6ed044fa9eadd090d3984
Author: Seth Forshee <seth.forshee@canonical.com>
Date:   Fri Jul 31 12:58:34 2015 -0500
UBUNTU: SAUCE: (namespace) block_dev: Support checking inode permissions in lookup_bdev()
When looking up a block device by path no permission check is
done to …
```
> fix compilation in ubuntu 4.15

- dev.c
- fuse_i.h
- pxd.c
- pxd.h
This address the IO fail during device attach.
device attach is split into two phases, first phase, setup everything except adding the disk to the kernel.
explicit export_device call exports the previous setup device.
```
[Mon Jul  5 14:16:59 2021] Device 953640569781256930 added with mode 0x0 fastpath 0 npath 0
[Mon Jul  5 14:16:59 2021] print_req_error: 14 callbacks suppressed
[Mon Jul  5 14:16:59 2021] blk_update_request: I/O error, dev pxd/pxd953640569781256930, sector 209715072 op 0x0:(READ) flags 0x80700 phys_seg 1 prio
[Mon Jul  5 14:16:59 2021] blk_update_request: I/O error, dev pxd/pxd953640569781256930, sector 209715072 op 0x0:(READ) flags 0x0 phys_seg 1 prio cla
[Mon Jul  5 14:16:59 2021] buffer_io_error: 2 callbacks suppressed
[Mon Jul …
```
> fix io fail during device attach

- pxd.h
In preparation of fastpath feature support in 2.9, bumping kernel version. define minimum fastpath driver support
and gate features outside of IO through feature flag.
goes with https://github.com/portworx/porx/pull/8036
Closes #
> minor changes based on 2.9 changes

- pxd.c
- pxd_bio.h
- pxd_bio_blkmq.c
- pxd_bio_makereq.c
- pxd_core.h
- pxd_fastpath.c
- pxd_fastpath.h
- pxd_fastpath_stub.h
In 2.10.0 branch
Closes #
https://portworx.atlassian.net/browse/PWX-21201 - fix compilation issue
https://portworx.atlassian.net/browse/PWX-21175 - fix kernel crash
This change passes the automation test consistently.
Fixes two issues.
1/ kernel crash
2/ compilation issue.
PASSED last 6 consecutive runs in the automation test.
> PWX-21175: handle kernel crash in fastpath + compilation fix

- pxd.c
- pxd.h
- pxd_bio.h
- pxd_bio_blkmq.c
- pxd_bio_makereq.c
- pxd_fastpath.c
- pxd_fastpath.h
- pxd_fastpath_stub.h
Closes # https://portworx.atlassian.net/browse/PWX-21175
PASSED last 6 consecutive runs in the automation test.
> PWX-21175: handle kernel crash in fastpath

- pxd.c
- pxd_bio.h
PWX-21201: part of compilation fixes for the fuse driver
While compiling in 3.10 kernel where fastpath is not supported, runs into a compilation failure.
This PR fixes it.
The issue is seen here: https://jenkins.portworx.dev/job/DEV/job/Porx-02/812/console
This above is in 2.10.0 branch, where this change needs to be cherry picked.
```
11:04:26    CC [M]  /home/carson/jenkins/jenkins.portworx.dev/workspace/DEV/Porx-02/src/github.com/portworx/porx/src/gdfs/px_fuse/pxd.o
11:04:27  /home/carson/jenkins/jenkins.portworx.dev/workspace/DEV/Porx-02/src/github.com/portworx/porx/src/gdfs/px_fuse/pxd.c: In function 'pxd_process_ioswitch_complete':
11:04:27 …
```
> PWX-21201: compilation fix

- io.c
Signed-off-by: Lakshmi Narasimhan Sundararajan <lsundararajan@purestorage.com>
```
/root/go/src/github.com/portworx/porx/src/gdfs/px_fuse/io.c:2263:12: error: 'SZ_4G' undeclared (first use in this function)
if (len > SZ_4G) {
```
above failure in : 4.15.0-20
some kernel versions have not defined the macro.
Closes #
> compile fix

- pxd.c
PX Fuse build fails on kernel 4.18.0-348.2.1.el8_5.x86_64.   This kernel backported changes from 5.10.  So add a define to handle that for this kernel.
Closes #
PWX-22075
> PWX-22075 Compile fix for 4.18.0-348.2.1.el8_5.x86_64 kernel.

- pxd.c
- pxd.h
Revising discard changes needed for virtual pxd device settings.
1/ fix discard granularity at 64K
2/ fix discard alignment at 64K
Closes #
> discard settings for dmthin

- pxd.c
PX fuse fails to compile on 5.15.0-1.el7.   implicit declaration of function ‘alloc_disk’  & error: ‘GENHD_FL_UP’ undeclared .  Use '__alloc_disk_node(...)'  & 'disk_live()' instead.
Closes #: PWX-22163
> PWX-22163: Compile fixes for 5.15.0-1.el7.

- pxd.h
FlagsetTest.reqflags fails which checks 
PXD_FLAGS_SYNC is same as sync_flags
> PWX-22291 Map PXD_FLAGS_SYNC to PXD_FLAGS_FUA

- io.c
Add force async processing for read requests as well. Btrfs reads are
too slow to be done in a single thread.
Closes #
> PWX-23492 add force_async handling for read requests

- pxd.c
Pxd block device is exported out using add_disk(). It looks like in some cases while we are in the middle on this lsblk or systemd-udevd starts using the device. And the add_disk() gets stuck because device is in use.So to avoid that keep the device q frozen until after add_disk() returns so that add_disk always finishes. 
Closes #
Issue is not readily reproducible.
To test: 
1. Create a repl2 volumes on node1, node2.
2. Start 'watch -n 1 lsblk' on both nodes.
3. Start 'watch pxctl host attach' on both nodes.
Device attachment will flip-flop among the 2 nodes with lsblk continuously trying to read from device. No issue so far.
> Unfreeze q after export

- dev.c
- fuse_i.h
- pxd.c
- pxd_fastpath.c
- pxd_fastpath.h
- pxd_fastpath_stub.h
handle recovering volume that are in suspended IO state.
During normal conditions this condition gets handled, but if for some unforeseen cases, if the block device in the kernel is frozen, and userspace does not complete in expected lines, it could leave both the block device hanging and IOs blocked forever.
This change addresses those scenarios, likely device is in suspend IO state,
1/ px restarts
2/ px stop and node wiped
3/ px up, but state inconsistent between kernel and userspace, and a device remove op gets submitted.
Test logs attached below, device suspended through debug interface.
Closes # …
> PWX-26219: improve recovery for suspended fastpath volumes

- pxd.c
- pxd_bio_blkmq.c
- pxd_fastpath.c
1/ pxd_remove has a race where it leaves block device queue context hanging while context are deleted.
This allows new IOs to take a long on an invalid/freed up context and this locks up the system.
2/ pxd_add - revised to only update metadata in the driver. No kernel side exposure gets made.
3/ pxd_export - revised to only export to kernel with the corresponding pxd device info.
Closes #
> cleanup device remove/export path for race conditions

- pxd.c
- pxd_bio_blkmq.c
It's incorrect to set minors to 256 since alloc_disk() was called with minors==1.
Closes #
> Set pxd minors to 1, pxd disk can't be partitioned

- pxd.c
For supporting kernel 5.15 and above we used the device_add_disk() api when attaching px device. This api takes an additional ref on the associated struct device. This ref gets dropped when del_gendisk is called.
In the old detach/free path del_gendisk is called only through device_release (pxd_dev_device_release) path. i.e. after the last ref is gone. To accommodate the conflicting requirements the solution was to make sure call to del_gendisk happens in the detach path - pxd_remove(). The release path would make the call again but would be a no-op.
The change was made because of this: https://lkml.iu.edu/hypermail/linux/kernel/1602.3/02004.html
It indicated that add_disk was being replaced with device_add_disk. But that doesn't seem to be the …
> use add_disk instead of device_add_disk

- pxd.c
- pxd_bio_blkmq.c
- pxd_compat.h
- pxd_fastpath.c
Signed-off-by: root <root@ip-10-13-1-49.pwx.dev.purestorage.com>
Build issues with 5.18.x/5.19.x kernels.  5.18.x/5.19.x removed include <linux/genhd.h>,   api changes for discard, removal of "write same" , etc...
Closes #
PWX-26675
**Special notes for your reviewer**
Waiting for dev jenkins to support these kernel so can run a full BVT tests.    
Note these changes:
REQ_OP_WRITE_ZEROES replaces REQ_OP_WRITE_SAME
pxd_bio_blkmq.c:fp_handle_specialops() changes dealing with "..write_same.."
BVTs:
BVT-MN-RESYNC-DMTHIN-FASTPATH Pass: https://jenkins.pwx.dev.purestorage.com/job/DMTHIN/view/DMTHIN-FASTPATH/job/DMTHIN-FASTPATH/job/BVT-MN-RESYNC-DMTHIN-FASTPATH-RELEASE/106/
Smoke 5.18 Pass: …
> PWX-26675: 5.19 and 5.18 changes/build issues.

- pxd.c
- pxd_core.h
Run detach as a work item from system queue since it can generate io and block. Wait the detach completion interruptible so the process can be killed while in process of detach.
Keep the device on the context list while detach work is in progress so new callers can find it and block until completion.
Closes #
> make detach interruptible and restart-able

- pxd_fastpath.c
harden cleanup/removal of pxd virtual device while from suspended state.
change order to release userspace suspends after iopath switch abort cleanup, as ordering matters.
Closes #
https://portworx.atlassian.net/browse/PWX-26219
> PWX-26219: handle device removal/wipe from suspended state

- Makefile.in
- pxd.c
- pxd_bio_blkmq.c
- pxd_compat.h
- pxd_fastpath.c
Support OCP 4.13 latest kernel which is 5.14.0-284.13.1.el9_2.
Closes #
PWX-31041
BTRFS also need to be added to the archive once testing is complete.
> PWX-31041: Changes to support 5.14.0-284.11.1.el9_2.

- pxd.c
- pxd_bio_blkmq.c
- pxd_compat.h
enable discard in 5.18.X.
Closes #
Manual tested on the following versions, build PASSED and fstrim works.
`5.18.0-1.el7.elrepo.x86_64`  
`5.18.0-1.el8.elrepo.x86_64`  
`5.18.15-1.el7.elrepo.x86_64` 
`5.18.15-1.el8.elrepo.x86_64` 
`5.19.0-1.el7.elrepo.x86_64`  
`5.19.0-1.el8.elrepo.x86_64`
> PWX-32731 remove 5.18 limit for discard

- Makefile.in
build_container+host combinations. Compile it separately and include it as binary blob.
Closes #
Before:
```
09:16:17  make[7]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
09:16:17    CC [M]  /root/workspace/release-build-jobs_gs-rel-2.13.8/go/src/github.com/portworx/porx/src/gdfs/px_fuse/pxd.o
09:16:19    CC [M]  /root/workspace/release-build-jobs_gs-rel-2.13.8/go/src/github.com/portworx/porx/src/gdfs/px_fuse/dev.o
09:16:19    CC [M]  /root/workspace/release-build-jobs_gs-rel-2.13.8/go/src/github.com/portworx/porx/src/gdfs/px_fuse/iov_iter.o
09:16:20    CC [M]  /root/workspace/release-build-jobs_gs-rel-2.13.8/go/src/github.com/portworx/porx/ …
```
> Using kbuild for building px_version.c causes ld failures on some

- pxd.c
- pxd_compat.h
Volume creation failure on 5.14
Closes #PWX-33031
Closes #PWX-33219
[Tue Aug 29 09:32:36 2023] BUG: scheduling while atomic: px-storage/2966058/0x00000002
[Tue Aug 29 09:32:36 2023] BUG: scheduling while atomic: px-storage/2966058/0x00000000
[Tue Aug 29 09:32:50 2023] BUG: scheduling while atomic: px-storage/2966784/0x00000002
[Tue Aug 29 09:32:50 2023] BUG: scheduling while atomic: px-storage/2966784/0x00000000
[Tue Aug 29 09:33:23 2023] BUG: scheduling while atomic: px-storage/2968136/0x00000002
[Tue Aug 29 09:33:23 2023] BUG: scheduling while atomic: px-storage/2968136/0x00000000
[Tue Aug 29 09:33:23 2023] BUG: scheduling while atomic: px-storage/2968145/0x00000002 …
> PWX-33031: Fix conditional for bio_set_dev existence; PWX-33219: Remove spinlock before calling pxd_bus_add_dev

- pxd.c
Seeing the issue with device and and lsblk again on FACD runs. I'm not sure what changed.
Putting this back to unblock the FACD automation.
Closes # https://portworx.atlassian.net/browse/PWX-32998
> Allow access to device queue only at the end of export

- Makefile.in
- io.c
Kernel 5.16 compilation fixes
Also include some fixes for handling the binary blob compilation. A bit hacky but does the job. Will try to come up a better way as a follow up.
Closes #
```
[root@ip-10-13-196-60 ~]# cat  /opt/pwx/oci/rootfs/home/px-fuse/pxfuse-bld.1695084353.out
Kernel version 5.16 supports fastpath.
Kernel version 5.16 supports blkmq driver model.
make -C /usr/src/kernels/5.16.14-1.el7.elrepo.x86_64  M=/home/px-fuse clean
make[1]: Entering directory '/usr/src/kernels/5.16.14-1.el7.elrepo.x86_64'
Kernel version 5.16 supports fastpath.
Kernel version 5.16 supports blkmq driver model.
make[1]: Leaving directory '/usr/src/kernels/5.16.14-1.el7.elrepo.x86_64' …
```
> kernel 5.16 compilation fixes

- pxd.c
Compilation issue caused by the addition of 'GENHD_FL_NO_PART' define in 5.15.132 kernel.    This exists as an "enum" in 5.17.x... so need to leave version check for 5.17.x
Closes #
PWX-33917
Ran the distro test for this kernel version using a private and the startup was fine.
> PWX-33917: fix 5.15.132-flatcar compilation issue.

- pxd.c
- pxd_compat.h
> PWX-31637: set iterator direction based on kernel version. Prevent older kernels builds from breaking.

- pxd.c
- pxd_core.h
1/ harden device removal path
--- freeze queue and mark device dead to ensure newer IOs do not continue to flow while device is being detached.
2/ fix the version report that does not account for the null char.
Closes # https://portworx.atlassian.net/browse/PWX-35419
1/ harden volume detach path
QA note: 
posted changes are running for 2 days with the issue not seen.
2/ also fix version report include null
```
// exact match
#cat px_version.c
const char *gitversion = "ln/minordevs:34234325345435345464565453524234242432423423423477";
Version: ln/minordevs:34234325345435345464565453524234242432423423423477
#
// more than 64
#cat px_version.c
const char *gitversion = …
```
> harden device remove

- Makefile.in
- pxd.c
- pxd_bio_blkmq.c
- pxd_compat.h
- pxd_fastpath.c
**ISSUE LOG**:
> KERNELPATH=/usr/src/linux-5.14.21-150500.55.39-obj/x86_64/default/  make
Kernel version 5.14 supports fastpath.
Kernel version 5.14 supports blkmq driver model.
make  -C /usr/src/linux-5.14.21-150500.55.39-obj/x86_64/default/  M=/home/ec2-user/home/px-fuse modules
make[1]: Entering directory '/usr/src/linux-5.14.21-150500.55.39-obj/x86_64/default'
Kernel version 5.14 supports fastpath.
Kernel version 5.14 supports blkmq driver model.
CC [M]  /home/ec2-user/home/px-fuse/pxd.o
/home/ec2-user/home/px-fuse/pxd.c: In function 'pxd_write_same_request':
/home/ec2-user/home/px-fuse/pxd.c:757:50: error: 'REQ_OP_WRITE_SAME' undeclared (first use in this function); did you mean 'REQ_OP_WRITE_ZEROES'?
rc = pxd_handle_device_limits(req, &size, &off, REQ_OP_WRITE_SAME); …
> PWX-35471: Changes to fix compilation issue with SUSE-15

- pxd.c
linux kernel version: 5.15.13-1.el7.elrepo.x86_64
```
[root@ip-10-13-160-160 ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
[root@ip-10-13-160-160 ~]#
```
bio_queue_enter: wait forever here for a condition that will never happen.
->blk_try_enter_queue -> will return false as percpu ref is marked dying.
-> wait event here forever which never happens.
```
wait_event(q->mq_freeze_wq, …
```
> PWX-35639: device removal got stuck

- dev.c
- pxd.c
- pxd.h
- pxd_core.h
handle device detach timeouts and subsequent attach incorrectly passing because of stale block device. 
Closes # PWX-35753
https://jenkins.pwx.dev.purestorage.com/job/Dev/job/Porx-08/116
```
block device detached
block device detachment scheduled and wait upon with a timeout
detachment action timeout
px-storage and px continues further with block device marked detached, while block device detachment still continues in the kernel block layer
new request to attach same block device
block device gets attached with a nop from the kernel fuse driver because of stale device that is being detached.
block attachment fails with no block device,  because previous stale device got …
```
> PWX-35753: handle device detach timeouts 

- pxd.c
- pxd_trace.h
Support for 5.14.0-427.el9.x86_64
Closes #
Part of PWX-36741
This is only for px-fuse and was already approved here:  https://github.com/portworx/px-fuse/pull/311
> PWX-36741: Compilation fixes for kernel '5.14.0-427.el9.x86_64'

- pxd.c
- pxd_bio.h
- pxd_bio_blkmq.c
- pxd_fastpath.c
- pxd_fastpath.h
perf opt
this PR addresses submission path optimization 
rootcause:
1/ resources underprovisioned for fastpath
2/ workqueues get throttled on io load.
3/ routing completion through kthreads also improves perf as the block device completions also use workqueues which 
get throttled at io load.
```
fio --blocksize=4k --numjobs=1 --ioengine=libaio --direct=1 --iodepth=128 --group_reporting --readwrite=randwrite --filesize=50G --end_fsync=1 --name=fiojob1 --filename=/dev/pxd/pxd911641125860330767 --name=fiojob2 --filename=/dev/pxd/pxd440908276035619902 --name=fiojob3 --filename=/dev/pxd/pxd9496376647647828 --name=fiojob4 --filename=/dev/pxd/pxd392231402311292274 --name=fiojob5 --filename=/dev/pxd/pxd394648074750351375 --name=fiojob6 …
```
> fastpath - submit path optimization

- pxd.c
fix tracebacks in kernels during dev add and removals
several context and kernel actions from ioctl calls during drive add/remove and px init are not clean.
below are collected tracebacks from linux kernel 6.5 with debug options enabled.
```
[Thu May 30 14:43:11 2024] BUG: sleeping function called from invalid context at lib/iov_iter.c:315
[Thu May 30 14:43:11 2024] in_atomic(): 1, irqs_disabled(): 0, non_block: 0, pid: 9301, name: px-storage
[Thu May 30 14:43:11 2024] preempt_count: 1, expected: 0
[Thu May 30 14:43:11 2024] RCU nest depth: 0, expected: 0
[Thu May 30 14:43:11 2024] 1 lock held by px-storage/9301:
[Thu May 30 14:43:11 2024]  #0: ffff967fd9f70018 (&ctx->lock#2){+.+.}-{3:3}, at: pxd_read_init+0x3b/0x1b0 [px]
[Thu May 30 14:43:11 2024] …
```
> PWX-37281: fix tracebacks in kernels during dev add and removals

- pxd.h
Update `PXD_MAX_DEVICES` from 512 to 1024.
This is done in order to support 1024 volume attach support.
https://purestorage.atlassian.net/browse/PWX-36999
> Update PXD_MAX_DEVICES to 1024

- dev.c
- kiolib.c
- pxd.c
* PWX-36736: Fix compile issues when building on kernels 6.8 & 6.9
* Only check RHEL_RELEASE on Rhel kernels. Fedora also has these defines.
* PWX-36736:  PR review changes.  Specify more to the limits structure for 6.9 compiles.
---------
This is a cherry pick:  https://github.com/portworx/px-fuse/pull/315
Closes #
PWX-36736
> PWX-36736: kernel v6.8/9 support (#315)

- pxd.c
- pxd.h
pxd devices currently hard code discard granularity which gets assigned to pxd device.
if those pxd devices receives discard which are not aligned to advertised real target devices, then userspace process can intelligently split and act correctly.
But while in fastpath, if the requests are not aligned to the actual device attribute then (some or all) discards become nop.
There currently exist no interface from userspace to configure this value dynamically.
For now, revising the discard param to the max supported value at the raw device end (which would be 2M),
Test logs are attached part of https://github.com/pure-px/porx/pull/13439/
Closes # PWX-37390
> PWX-37390: revise discard granularity for pxd devices

- Makefile.in
- pxd.c
- pxd_bio_blkmq.c
- pxd_fastpath.c
- pxd_trace.h
The following is the compilation issue
`/root/px-fuse/pxd.c:402:12: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
.open   = pxd_open,
^~~~~~~~
/root/px-fuse/pxd.c:402:12: note: (near initialization for ‘pxd_bd_ops.open’)
/root/px-fuse/pxd.c:403:14: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
.release  = pxd_release,
^~~~~~~~~~~`
For SLES 15 SP6, the following is the definition of open and release in `struct block_device_operations`
`int (*open)(struct gendisk *disk, blk_mode_t mode);`
`void (*release)(struct gendisk *disk);`
This PR adds new define `__SUSE_GTE_SP6__` to fix this. As part of adding this new define, an existing define was changed from `__SUSE_GT_SP4__` to `D__SUSE_EQ_SP5__` because …
> PWX-40500: Fix compilation issues with SLES 15 SP6 - kernel 6.4.0-150……600.23.25-default

- pxd.c
~~iov_iter’s direction is reversed in RHEL 9.5 (possibly because of the backported changes). For eg)~~
~~kernel-5.14.0-503.14.1.el9_5~~
~~file include/linux/uio.h~~
~~Add a new define to handle only for RHEL 9.5~~
Rootcause is a bug in the original existing code with regards to direction usage. A sanity check on the direction in recent kernels exposed the bug. It is fixed now.
Closes # PWX-41114
> PWX-41114: handle iov_iter direction changes in RHEL9.5

- Makefile.in
- pxd.c
- pxd_trace.h
What this PR does / why we need it:
This fixes compilation issues for SLE Micro 6.1 by adding `__SLE_MICRO_EQ_6_1__`
The following is the compilation error.
```
/root/sebas/px-fuse/pxd.c:398:35: error: initialization of ‘int (*)(struct gendisk *, blk_mode_t)’ {aka ‘int (*)(struct gendisk *, unsigned int)’} from incompatible pointer type ‘int (*)(struct block_device *, fmode_t)’ {aka ‘int (*)(struct block_device *, unsigned int)’} [-Wincompatible-pointer-types]
398 |         .open                   = pxd_open,
|                                   ^~~~~~~~
/root/sebas/px-fuse/pxd.c:398:35: note: (near initialization for ‘pxd_bd_ops.open’)
/root/sebas/px-fuse/pxd.c:399:35: error: initialization of ‘void (*)(struct gendisk *)’ from incompatible pointer type ‘void (*)(struct gendisk *, …
```
> PWX-41245: Fix compilation issue for SLE Micro 6.1

- Makefile.in
- pxd.c
- pxd_trace.h
Fix compilation issue for SLE 6.0 and 6.1. There was a change in requirement to support SLE 6.0 as well.
the following is the compiler error on SLE 6.0
```
KERNELPATH=/root/linux-6.4.0-20-obj/x86_64/default/ make
Kernel version 6.4 supports fastpath.
Kernel version 6.4 supports blkmq driver model.
make  -C /root/linux-6.4.0-20-obj/x86_64/default/  M=/root/sebas/px-fuse modules
warning: the compiler differs from the one used to build the kernel
The kernel was built by: gcc (SUSE Linux) 13.3.0
You are using:           gcc (SUSE Linux) 14.2.1 20241007 [revision 4af44f2cf7d281f3e4f3957efce10e8b2ccb2ad3]
Kernel version 6.4 supports fastpath.
Kernel version 6.4 supports blkmq driver model.
CC [M]  /root/sebas/px-fuse/pxd.o …
```
> PWX-41275: fix compilation issue for SLE micro 6.1 (as well as 6.0)

- pxd.c
- pxd.h
PWX-39098.
For Encapsulated devices, control plane needs to issue an ioctl through which we can detach devices attached locally after completing CP clean up.
introduce a ioctl to do the device clean up.
> PWX-39098: Add ioctl to detach a device on the local node

- dev.c
Revert changes for returning -EFAULT on user iovec count reaching 0 but there is data to be copied from bvecs since it is a valid scenario for aggr volumes.
Closes #
> Pwx 42778 fix

- pxd.c
- pxd_compat.h
- pxd_fastpath.c
px-fuse does not compile for kernel 6.11
Closes # PWX-42349 , PTX-29484
Ubuntu 24.04 LTS
```
root@ip-10-38-36-210:~/px-fuse# KERNELPATH=/usr/src/linux-headers-$(uname -r) make 
Kernel version 6.11 supports fastpath.
Kernel version 6.11 supports blkmq driver model.
make  -C /usr/src/linux-headers-6.11.0-17-generic  M=/root/px-fuse modules
make[1]: Entering directory '/usr/src/linux-headers-6.11.0-17-generic'
warning: the compiler differs from the one used to build the kernel
The kernel was built by: x86_64-linux-gnu-gcc-13 (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
You are using:           gcc-13 (Ubuntu 13.2.0-23ubuntu4) 13.2.0
Kernel version 6.11 supports fastpath.
Kernel …
```
> PWX-42349: Fix fuse compilation for kernel 6.11.0 and 6.11.9

- pxd_bio_blkmq.c
bio_associate_blkg_from_css() is not available in older kernels use bio_associate_blkcg()
Closes # PWX-42957
> PWX-42957: Fix compilation for kern 4.15

- pxd_bio_blkmq.c
If clone_bio->bi_blkg is not initialised associate clone bio with block group root css
Closes # PWX-42957
> PWX-42957: Associate clone bio with block group root css 

- pxd_bio_blkmq.c
Closes # PWX-43148
```
[root@ip-10-38-35-103 px-fuse]# KERNELPATH=/usr/src/kernels/$(uname -r) make
Kernel version 5.14 supports fastpath.
Kernel version 5.14 supports blkmq driver model.
make  -C /usr/src/kernels/5.14.0-284.30.1.el9_2.x86_64  M=/root/px-fuse modules
make[1]: Entering directory '/usr/src/kernels/5.14.0-284.30.1.el9_2.x86_64'
Kernel version 5.14 supports fastpath.
Kernel version 5.14 supports blkmq driver model.
CC [M]  /root/px-fuse/pxd.o
CC [M]  /root/px-fuse/dev.o
CC [M]  /root/px-fuse/iov_iter.o
CC [M]  /root/px-fuse/px_version.o
CC [M]  /root/px-fuse/kiolib.o
CC [M]  /root/px-fuse/pxd_bio_makereq.o
CC [M]  /root/px-fuse/pxd_bio_blkmq.o
CC [M] …
```
> PWX-43148: cherrypick fastpath fix to comcast branch

- pxd_bio_blkmq.c
Closes # PWX-43148
```
[root@ip-10-38-35-103 px-fuse]# KERNELPATH=/usr/src/kernels/$(uname -r) make
Kernel version 5.14 supports fastpath.
Kernel version 5.14 supports blkmq driver model.
make  -C /usr/src/kernels/5.14.0-284.30.1.el9_2.x86_64  M=/root/px-fuse modules
make[1]: Entering directory '/usr/src/kernels/5.14.0-284.30.1.el9_2.x86_64'
Kernel version 5.14 supports fastpath.
Kernel version 5.14 supports blkmq driver model.
CC [M]  /root/px-fuse/pxd.o
CC [M]  /root/px-fuse/dev.o
CC [M]  /root/px-fuse/iov_iter.o
CC [M]  /root/px-fuse/px_version.o
CC [M]  /root/px-fuse/kiolib.o
CC [M]  /root/px-fuse/pxd_bio_makereq.o
CC [M]  /root/px-fuse/pxd_bio_blkmq.o
CC [M] …
```
> PWX-43148: cherrypick fastpath fix to v3.0.1

- pxd_bio_blkmq.c
- pxd_core.h
- pxd_fastpath.c
This PR has fixes for PWX-42357, PWX-42656, PWX-42637 and PWX-42628 since I don't have a UT that validates only one.
**UT notes for PWX-42357**
**Without fix**
```
./t --gtest_filter=*IoFailureTriggeredFailoverNoScale*
Note: Google Test filter = *IoFailureTriggeredFailoverNoScale*
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from FailoverTest
[ RUN      ] FailoverTest.IoFailureTriggeredFailoverNoScale
25600+0 records in
25600+0 records out
104857600 bytes (105 MB, 100 MiB) copied, 0.407803 s, 257 MB/s
mke2fs 1.44.1 (24-Mar-2018)
Discarding device blocks: done                            
Creating filesystem with 25600 4k blocks and 25600 inodes
Allocating group tables: done                            
Writing inode tables: …
```
> PWX-42357, PWX-42656, PWX-42637 and PWX-42628

- pxd.c
- pxd.h
Linked with https://github.com/pure-px/porx/pull/14721
***History of discard handling in the kernel***
```
commit 48920ff2a5a940cd07d12cc79e4a2c75f1185aee
Author: Christoph Hellwig <hch@lst.de>
Date:   Wed Apr 5 19:21:23 2017 +0200
block: remove the discard_zeroes_data flag
Now that we use the proper REQ_OP_WRITE_ZEROES operation everywhere we can
kill this hack.
Signed-off-by: Christoph Hellwig <hch@lst.de>
Reviewed-by: Martin K. Petersen <martin.petersen@oracle.com>
Reviewed-by: Hannes Reinecke <hare@suse.com>
Signed-off-by: Jens Axboe <axboe@fb.com>
commit 98262f2762f0067375f83824d81ea929e37e6bfe
Author: Martin K. Petersen <martin.petersen@oracle.com>
Date:   Thu Dec 3 09:24:48 2009 +0100
block: Allow devices to indicate whether discarded blocks …
```
> fix discard size/granularity limits

- pxd_bio_blkmq.c
- pxd_bio_makereq.c
* On some kernel versions (ubuntu 22.04, 5.15.0-67-generic), if the fastpath has issues because of network, the error returned in the BIO's completion callback is -ENOLINK (-67). Trigger a failover if we can.
```
[Thu Apr 24 21:34:21 2025] blkmq fastpath: FAILED IO nvme0n1 (err=-67): dev m 1 g 1031823872070688543 wr at 52682752 len 0 bytes 0 pages flags 0x8800
[Thu Apr 24 21:34:21 2025] blkmq fastpath: FAILED IO nvme0n1 (err=-67): dev m 1 g 1031823872070688543 wr at 56987648 len 0 bytes 0 pages flags 0x8800
[Thu Apr 24 21:34:21 2025] blkmq fastpath: FAILED IO nvme0n1 (err=-67): dev m 1 g 1031823872070688543 wr at 540672 len 0 bytes 0 pages flags 0x8800
[Thu Apr 24 21:34:21 2025] blkmq fastpath: FAILED IO nvme0n1 (err=-67): dev m 1 g …
```
> PWX-43578: trigger failover on -ENOLINK if fastpath is flakey

- pxd.c
- pxd_compat.h
- pxd_fastpath.c
Closes # PWX-44121
build on
Operating System: Red Hat Enterprise Linux CoreOS 9.6.20250402-0 (Plow)
CPE OS Name: cpe:/o:redhat:enterprise_linux:9::baseos
Kernel: Linux 5.14.0-570.10.1.el9_6.x86_64
```
[root@localhost px-fuse]# KERNELPATH=/usr/src/kernels/5.14.0-570.17.1.el9_6.x86_64/ make
Kernel version 5.14 supports fastpath.
Kernel version 5.14 supports blkmq driver model.
make  -C /usr/src/kernels/5.14.0-570.17.1.el9_6.x86_64/  M=/var/roothome/px-fuse modules
make[1]: Entering directory '/usr/src/kernels/5.14.0-570.17.1.el9_6.x86_64'
Kernel version 5.14 supports fastpath.
Kernel version 5.14 supports blkmq driver model.
Kernel version 5.14 supports fastpath.
Kernel version 5.14 supports blkmq driver …
```
> PWX-44121: Fix fuse build for RHEL 9.6 + 5.14.0-570.17.1.el9_6

- pxd.c
- pxd_compat.h
- pxd_fastpath.c
Reverts portworx/px-fuse#362
Not going as part of 3.3.0
> Revert "PWX-44121: Fix fuse build for RHEL 9.6 + 5.14.0-570.17.1.el9_6"

- pxd.h
Closes # PWX-44986
root@ip-10-38-34-35:~/px-fuse# runc exec -t portworx pxd -v 
Version: v3.3.0:1mb-discard-fix
root@ip-10-38-34-35:~/px-fuse# 
root@ip-10-38-34-35:~/px-fuse# pxctl v c vol1 --nodes LocalNode 
Volume successfully created: 971456823351722830
root@ip-10-38-34-35:~/px-fuse# pxctl host attach vol1 
Volume successfully attached at: /dev/pxd/pxd971456823351722830
root@ip-10-38-34-35:~/px-fuse# 
root@ip-10-38-34-35:~/px-fuse# blkdiscard /dev/pxd/pxd971456823351722830 
root@ip-10-38-34-35:~/px-fuse# 
root@ip-10-38-34-35:~/px-fuse# pxctl status 
Status: PX is operational
Telemetry: Disabled or Unhealthy
Metering: Disabled or Unhealthy
License: Trial (expires in …
> PWX-44986: cherry-pick 1mb discard fix to v3.3.1

- pxd_compat.h
**What this PR does / why we need it**: 
This PR fixes re-declaration of exisiting methods issue of method call `bio_set_op_attrs` for rhel 9.2.
Closes #
- [5.14.0-284.30.1.el9_2](https://purestorage.atlassian.net/browse/PWX-45490)
- [5.14.0-362.24.1.el9_3](https://purestorage.atlassian.net/browse/PWX-45521)
> 9.2 rhel fix

- pxd.c
- test/pxd_test.cc
Initial Error:
```
pxd.c: In function 'pxd_export':
pxd.c:1662:9: error: too few arguments to function 'blk_mq_unfreeze_queue'
1662 |         blk_mq_unfreeze_queue(pxd_dev->disk->queue);
|         ^~~~~~~~~~~~~~~~~~~~~
In file included from pxd_core.h:7,
from pxd.c:41:
/usr/src/linux-headers-6.14.0-061400-generic/include/linux/blk-mq.h:932:1: note: declared here
932 | blk_mq_unfreeze_queue(struct request_queue *q, unsigned int memflags)
| ^~~~~~~~~~~~~~~~~~~~~
make[4]: *** [/usr/src/linux-headers-6.14.0-061400-generic/scripts/Makefile.build:207: pxd.o] Error 1
make[3]: *** [/usr/src/linux-headers-6.14.0-061400-generic/Makefile:2001: .] Error 2
make[2]: *** [/usr/src/linux-headers-6.14.0-061400-generic/Makefile:251: __sub-make] Error 2
make[2]: Leaving directory '/root/px-fuse'
make[1]: …
```
> Added fixes to handle ubuntu 24.04 keernel 6.14.x errors

- pxd_bio_blkmq.c
- test/pxd_test.cc
This PR fixes issue with photon OS compatibility with px-fuse by removing calls involving blkcg_root_css since this symbol is present but not exported in kernel module below 5.0.0 version. 
Hence, the compiled sources on any OS below 5.0.0 kernel version do not support this operation.
```
root@ip-10-13-241-210 [ ~/px-fuse ]# uname -r
4.19.325-1.ph3
root@ip-10-13-241-210 [ ~/px-fuse ]# sudo insmod px.ko
insmod: ERROR: could not insert module px.ko: Unknown symbol in module
root@ip-10-13-241-210 [ ~/px-fuse ]# lsmod | grep px
root@ip-10-13-241-210 [ ~/px-fuse ]# dmesg -e | grep px
...
...
[  +0.001011] pxd_control_open: pxd-control-0(1) open OK
[  +0.000003] pxd_read_init: pxd-control-0 init OK 0 devs version 12
[  +2.001573] pxd_finish_remove: dev 1 …
```
> Fix photon OS blkcg_root_css not found issue
